package main

func init() {
	configTemplates["bam"] = defaultConfig
	configTemplates["iptables"] = `# Generated by BAM!
*nat
-A PREROUTING -p tcp -m tcp --dport 80 -j REDIRECT --to-ports {{.ProxyPort}}
-A OUTPUT -d 127.0.0.1 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports {{.ProxyPort}}
COMMIT
`
	configTemplates["help"] = `
Available generate options are 'bam' and 'iptables'.

# bam

Generate configuration file with default values for bam.

Example:

    bam -generate bam


# iptables

Generate iptables rules for forwarding incoming connections to bam's proxy.

Example:

    bam -generate iptables > iptables.rules

IMPORTANT: If you are using a custom config file you also must use -config option.

Apply these rules to iptables using the following command:

    sudo iptables-restore < iptables.rules

Check the rules applied to iptables by executing:

    sudo iptables -t nat -L -n

In order to get BAM! working properly you also will need to install localtld:

    https://github.com/jweslley/localtld
`
}
