package main

import (
	"fmt"
	"os"
	"text/template"
)

func configuration(c *Config) {
	f, err := os.Create("bam.iptables.rules")
	fail(err)
	defer f.Close()

	var t = template.Must(template.New("iptables").Parse(iptables))
	t.Execute(f, c)

	fmt.Print(`Generated file bam.iptables.rules

Apply these rules to iptables using the following command:

    sudo iptables-restore < bam.iptables.rules

Check the rules applied to iptables by executing:

    sudo iptables -t nat -L -n

In order to get BAM! working properly you also will need to install localtld:

    https://github.com/jweslley/localtld
`)
}

const iptables = `# Generated by BAM!
*nat
-A PREROUTING -p tcp -m tcp --dport 80 -j REDIRECT --to-ports {{.ProxyPort}}
-A OUTPUT -d 127.0.0.1 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports {{.ProxyPort}}
COMMIT
`
